production:                                                                      
  adapter: mysql2                                                                
  encoding: utf8                                                                 
  collation: utf8_general_ci                                                     
  host: 127.0.0.1                                                                
  username: easycreate                                                             
  password: easy                                                           
  database: easycreate                                                            
  reconnect: true 

development:
  adapter: mysql2                                                                
  encoding: utf8                                                                 
  collation: utf8_general_ci                                                     
  host: 127.0.0.1                                                                
  username: root 
  password: root 
  database: easycreate_development
  reconnect: true 

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

